cesar:
  baseurl: ${CESAR_BASEURL:http://localhost:8080}
  crypto :
    salt : XXXXX-S ecretKey-XXXXX

spring:
  datasource:
    driver-class-name : ${CESAR_DATABASE_DRIVER:com.mysql.jdbc.Driver}
    url : jdbc:mysql://${CESAR_DATABASE_HOST:localhost}:${CESAR_DATABASE_PORT:3306}/${CESAR_DATABASE_NAME:mixit}
    username : ${CESAR_DATABASE_USERNAME:mixit}
    password : ${CESAR_DATABASE_PASSWORD:mixit}

  jpa :
    ddl-auto : validate
    hibernate.naming_strategy : org.hibernate.cfg.EJB3NamingStrategy
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect

oauth:
  google:
    apiKey : XXXXX-SecretKey-XXXXX
    clientSecret : XXXXX-SecretKey-XXXXX
  twitter:
    apiKey : XXXXX-SecretKey-XXXXX
    clientSecret : XXXXX-SecretKey-XXXXX

---
spring:
  profiles: default
cesar:
  initializeDataWhenDbEmpty : true
---
spring:
  profiles: staging
  datasource:
      url : jdbc:mysql://${CESAR_DATABASE_HOST:localhost}:${CESAR_DATABASE_PORT:3306}/${CESAR_DATABASE_NAME:mixit}?sslca=${CESAR_DATABASE_SSL_CA:/conf/ssl/cleardb-ca-cert.pem}&sslcert=${CESAR_DATABASE_SSL_CERT:/conf/ssl/cleardb-cert.pem}&sslkey=${CESAR_DATABASE_SSL_KEY:/conf/ssl/cleardb_id-key.pem}&reconnect=true
server:
  port: 80

---
spring:
  profiles: prod
  datasource:
      url : jdbc:mysql://${CESAR_DATABASE_HOST:localhost}:${CESAR_DATABASE_PORT:3306}/${CESAR_DATABASE_NAME:mixit}?sslca=${CESAR_DATABASE_SSL_CA:/conf/ssl/cleardb-ca-cert.pem}&sslcert=${CESAR_DATABASE_SSL_CERT:/conf/ssl/cleardb-cert.pem}&sslkey=${CESAR_DATABASE_SSL_KEY:/conf/ssl/cleardb_id-key.pem}&reconnect=true
server:
  port: 80